# Generated by Django 3.2.8 on 2021-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='students/%Y/%m'),
        ),
    ]
